name: Windows Build (jlink)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build runtime image (jlink)
        shell: bash
        run: |
          ./gradlew.bat --no-daemon clean jlink

      # jlink 결과: build/image/ 아래에 생성
      - name: Zip runtime image
        shell: bash
        run: |
          cd build
          powershell -Command "Compress-Archive -Path image -DestinationPath TodoProgram-windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TodoProgram-windows
          path: build/TodoProgram-windows.zip
